// Generates stubs.c: every OpenGL 1.1 entry point (the prototypes in
// MinGW's GL/gl.h) that opengl32.c does not implement, as a function that
// reports itself once and does nothing. Programs bind all of them with
// GetProcAddress (Quake II's ref_gl takes the address of each), so all have
// to exist, with the right stdcall argument size.
//
//   node native/opengl32/gen-stubs.mjs GL/gl.h opengl32.c > stubs.c
import { readFileSync } from 'node:fs';

const [glh, impl] = process.argv.slice(2).map((p) => readFileSync(p, 'latin1'));
const done = new Set([...impl.matchAll(/\bAPIENTRY\s+(gl\w+)\s*\(/g)].map((m) => m[1]));
const out = ['/* Generated by gen-stubs.mjs: OpenGL 1.1 functions opengl32.c does not implement. */', '#include "gl.h"', ''];
for (const m of glh.matchAll(/WINGDIAPI\s+([\w\s*]+?)\s*APIENTRY\s+(gl\w+)\s*\(([^)]*)\);/g)) {
  const [, ret, name, params] = m;
  if (done.has(name)) continue;
  const args = params.trim() === 'void' ? 'void' : params.split(',').map((p, i) => `${p.trim().replace(/\s*\w+$/, '')} a${i}`).join(', ');
  const body = ret.trim() === 'void' ? `gl_unimplemented("${name}");` : `gl_unimplemented("${name}"); return 0;`;
  out.push(`${ret.trim()} APIENTRY ${name}(${args}) { ${body} }`);
}
process.stdout.write(out.join('\n') + '\n');
