#!/bin/sh
# Derives config.h for the Emscripten build of Wine's Unix side from the
# host build's config.h: header checks are redone against Emscripten's
# headers, and function checks are limited to what Emscripten provides.
#   gen-config.sh HOST_CONFIG_H OUT_CONFIG_H
set -eu
in=$1
out=$2
keep_funcs="HAVE_CLOCK_GETTIME HAVE_FUTIMENS HAVE_FUTIMES HAVE_GETADDRINFO HAVE_PIPE2 HAVE_SCHED_YIELD
HAVE_SIGPROCMASK HAVE_STRUCT_STAT_ST_ATIM HAVE_STRUCT_STAT_ST_CTIM HAVE_STRUCT_STAT_ST_MTIM HAVE___BUILTIN_POPCOUNT
HAVE_STDINT_H HAVE_INTTYPES_H HAVE_STDIO_H HAVE_STDLIB_H HAVE_STRINGS_H HAVE_STRING_H HAVE_UNISTD_H"
# Headers Emscripten ships without the functions behind them.
deny="HAVE_SYS_EPOLL_H HAVE_SCSI_SCSI_H HAVE_SCSI_SCSI_IOCTL_H HAVE_SCSI_SG_H HAVE_SYS_MTIO_H HAVE_SYS_SHM_H
HAVE_SYS_IPC_H HAVE_SYS_SYSCALL_H HAVE_SYSCALL_H HAVE_SYS_XATTR_H HAVE_LINK_H HAVE_MNTENT_H HAVE_SYS_MOUNT_H"
tmp=$(mktemp -d)
{
  echo "/* Generated by native/wine-unix/gen-config.sh from $in. */"
  while IFS= read -r line; do
    case $line in
      "#define HAVE_"*)
        name=$(echo "$line" | awk '{print $2}')
        case " $(echo $deny) " in *" $name "*) echo "/* no implementation in Emscripten: $name */"; continue ;; esac
        case " $(echo $keep_funcs) " in *" $name "*) echo "$line"; continue ;; esac
        case $name in
          *_H)
            # HAVE_SYS_EPOLL_H -> sys/epoll.h; HAVE_LINUX_MAJOR_H -> linux/major.h
            hdr=$(echo "${name#HAVE_}" | sed 's/_H$//' | tr 'A-Z' 'a-z')
            for cand in "$(echo "$hdr" | sed 's/^\(sys\|linux\|net\|netinet\|arpa\|asm\|scsi\|netipx\|valgrind\)_/\1\//; s/^net_if_/net\/if_/').h"; do
              printf '#include <%s>\n' "$cand" > "$tmp/t.c"
              if emcc -E "$tmp/t.c" -o /dev/null 2>/dev/null; then echo "$line"; fi
            done
            ;;
          *) echo "/* dropped for Emscripten: $name */" ;;
        esac
        ;;
      *) echo "$line" ;;
    esac
  done < "$in"
  # FreeType comes from Emscripten's port, linked in (see inproc/freetype.c).
  echo '#define HAVE_FT2BUILD_H 1'
  echo '#define SONAME_LIBFREETYPE "libfreetype.so.6"'
} > "$out"
rm -rf "$tmp"
