#!/usr/bin/env python3
"""Generates typed thunks for the NT calls the module exports to the host.

The host routes some of the guest's system calls (synchronization, the
registry, security) to Wine's Unix code in the module. It passes their
arguments as an array of slots, as they are in the guest: 32-bit stack
slots on i386 (two for a 64-bit value), one 64-bit slot per argument on
x86_64. Each thunk calls its function with the declared parameter types, so
C does the conversions (on wasm64, JavaScript would otherwise need each
argument's exact WebAssembly type). Prototypes come from the functions'
definitions in the prepared sources.

    gen-ntcalls.py OUT.c i386|x86_64 NAMES FILE.c...

NAMES lists the calls, one per line; their prototypes are taken from the
definitions in the FILE.c arguments.

Writes OUT.c with `wasm_nt_call(index, args)` and OUT.json, the names by
index.
"""

import json
import os
import re
import sys

out_path, arch, names_file = sys.argv[1:4]
files = sys.argv[4:]
wide = arch == 'x86_64'

SIXTY_FOUR = {'LONGLONG', 'ULONGLONG', 'INT64', 'UINT64', 'DWORD64', 'ULONG64', 'LONG64', 'LARGE_INTEGER',
              'ULARGE_INTEGER'}

defn_re = re.compile(r'^NTSTATUS\s+WINAPI\s+(Nt\w+)\s*\(([^;{]*?)\)\s*\{', re.M | re.S)
protos = {}
for f in files:
    text = re.sub(r'/\*.*?\*/', '', open(f, errors='replace').read(), flags=re.S)
    for name, params in defn_re.findall(text):
        protos.setdefault(name, ' '.join(params.split()))


def split_params(params):
    if params in ('', 'void', 'VOID'):
        return []
    out, depth, cur = [], 0, ''
    for ch in params:
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
            continue
        depth += ch in '(['
        depth -= ch in ')]'
        cur += ch
    out.append(cur.strip())
    return out


def param_type(p):
    if '(' in p:
        return 'void *'
    p = re.sub(r'\[[^\]]*\]$', '*', p).strip()
    m = re.match(r'^(.*?)(\w+)$', p)
    if m and m.group(1).strip() and not m.group(1).strip().endswith(('struct', 'enum', 'union')):
        return m.group(1).strip()
    return p


wanted = [n.strip() for n in open(names_file) if n.strip()]
missing = [n for n in wanted if n not in protos]
if missing:
    sys.exit(f'gen-ntcalls.py: no definition found for {", ".join(missing)}')
names = sorted(set(wanted))
lines = [
    '/* Generated by native/wine-unix/gen-ntcalls.py from the definitions in the prepared sources. */',
    '#include "config.h"',
    '#include <stdarg.h>',
    '#include "ntstatus.h"',
    '#define WIN32_NO_STATUS',
    '#include "unix_private.h"',
    '#include <emscripten.h>',
    '',
]
for name in names:
    args, slot = [], 0
    for p in split_params(protos[name]):
        t = param_type(p)
        base = t.replace('const', '').replace('*', '').strip()
        if '*' not in t and base in SIXTY_FOUR and not wide:
            args.append(f'*({t} *)&a[{slot}]')
            slot += 2
        elif '*' not in t and base in ('LARGE_INTEGER', 'ULARGE_INTEGER'):
            args.append(f'*({t} *)&a[{slot}]')
            slot += 1
        else:
            args.append(f'({t})a[{slot}]')
            slot += 1
    lines.append(f'static NTSTATUS call_{name}( const ULONG_PTR *a ) {{ return {name}( {", ".join(args)} ); }}')
lines += ['', 'static NTSTATUS (*const calls[])( const ULONG_PTR * ) =', '{']
lines += [f'    call_{n},' for n in names]
lines += ['};', '',
          'EMSCRIPTEN_KEEPALIVE NTSTATUS wasm_nt_call( unsigned int index, const ULONG_PTR *args )',
          '{',
          '    if (index >= ARRAY_SIZE(calls)) return STATUS_INVALID_SYSTEM_SERVICE;',
          '    return calls[index]( args );',
          '}', '']
open(out_path, 'w').write('\n'.join(lines))
json.dump(names, open(os.path.splitext(out_path)[0] + '.json', 'w'))
print(f'gen-ntcalls.py: {len(names)} NT calls', file=sys.stderr)
