#!/usr/bin/env python3
"""Generates typed system call thunks for win32u's Unix side.

Wine's x86 syscall dispatcher calls each table entry with the arguments
copied from the caller's stack, whatever the function's signature.
WebAssembly checks the signature of every indirect call, so this generates
one thunk per system call that reads the 32-bit stack slots and calls the
function with its declared parameter types (two slots for a 64-bit value).
For the 64-bit build (ARCH x86_64) the slots are 8 bytes, one per argument,
from Wine's Win64 table. The prototypes come from Wine's headers; each one
is checked against the argument byte count in Wine's own table
(win32syscalls.h).

    gen-syscalls.py WINE_SRC OUT.c [i386|x86_64]
"""

import glob
import os
import re
import sys

wine_src, out_path = sys.argv[1:3]
wide = len(sys.argv) > 3 and sys.argv[3] == 'x86_64'
table = open(os.path.join(wine_src, 'dlls/win32u/win32syscalls.h')).read()

if wide:
    body = table[table.index('#ifdef _WIN64'):table.index('#define ALL_SYSCALLS ALL_SYSCALLS32')]
else:
    body = table[table.index('#define ALL_SYSCALLS32'):table.index('#ifdef _WIN64')]
SLOT = 8 if wide else 4
entries = [(int(i, 16), n, int(a)) for i, n, a in re.findall(r'SYSCALL_ENTRY\(\s*(0x[0-9a-f]+),\s*(\w+),\s*(\d+)\s*\)', body)]
stubs = set(re.findall(r'SYSCALL_STUB\(\s*(\w+)\s*\)', table))

headers = (glob.glob(os.path.join(wine_src, 'include/*.h')) + glob.glob(os.path.join(wine_src, 'include/ddk/*.h'))
           + glob.glob(os.path.join(wine_src, 'dlls/win32u/*.h')))
protos = {}
proto_re = re.compile(r'\b(?:W32KAPI|NTSYSAPI|extern)?\s*([A-Za-z_][\w ]*?\**)\s+WINAPI\s+(Nt\w+)\s*\(([^;{]*?)\)\s*;', re.S)
for h in headers:
    text = re.sub(r'/\*.*?\*/', '', open(h, errors='replace').read(), flags=re.S)
    for ret, name, params in proto_re.findall(text):
        protos.setdefault(name, (ret.strip(), ' '.join(params.split())))

SIXTY_FOUR = {'LONGLONG', 'ULONGLONG', 'INT64', 'UINT64', 'DWORD64', 'ULONG64', 'LONG64', 'LARGE_INTEGER',
              'ULARGE_INTEGER', 'D3DGPU_VIRTUAL_ADDRESS', 'double', 'DOUBLE'}


def split_params(params):
    if params in ('', 'void', 'VOID'):
        return []
    out, depth, cur = [], 0, ''
    for ch in params:
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
            continue
        depth += ch in '(['
        depth -= ch in ')]'
        cur += ch
    out.append(cur.strip())
    return out


def param_type(p):
    """The type of a parameter declaration, without its name."""
    if '(' in p:  # function pointer: keep it whole, it is pointer-sized
        return 'void *'
    p = re.sub(r'\[[^\]]*\]$', '*', p).strip()
    m = re.match(r'^(.*?)(\w+)$', p)
    if m and (m.group(1).strip() and not m.group(1).strip().endswith(('struct', 'enum', 'union'))):
        t = m.group(1).strip()
    else:
        t = p
    return t


lines = [
    '/* Generated by native/wine-unix/gen-syscalls.py from Wine\'s win32syscalls.h and headers. */',
    '#include "win32syscalls_includes.h"',
    '',
]
thunks = []
problems = []
for sid, name, argbytes in entries:
    fn = f'thunk_{name}'
    if name in stubs or name not in protos:
        if name not in stubs:
            problems.append(f'{name}: no prototype found')
        lines.append(f'static ULONG_PTR {fn}( const ULONG_PTR *a ) {{ return STATUS_NOT_IMPLEMENTED; }}')
        thunks.append(fn)
        continue
    ret, params = protos[name]
    args, slot = [], 0
    for p in split_params(params):
        t = param_type(p)
        base = t.replace('const', '').replace('*', '').strip()
        if '*' not in t and base in ('double', 'DOUBLE', 'float', 'FLOAT') and wide:
            # Win64 passes the first four in xmm registers, not read here.
            problems.append(f'{name}: floating-point parameter')
            args.append(f'*({t} *)&a[{slot}]')
            slot += 1
        elif '*' not in t and base in SIXTY_FOUR and wide:
            args.append(f'({t})a[{slot}]' if base not in ('LARGE_INTEGER', 'ULARGE_INTEGER') else f'*({t} *)&a[{slot}]')
            slot += 1
        elif '*' not in t and base in SIXTY_FOUR:
            if base in ('double', 'DOUBLE'):
                problems.append(f'{name}: floating-point parameter')
            args.append(f'*({t} *)&a[{slot}]')
            slot += 2
        elif '*' not in t and base in ('float', 'FLOAT'):
            args.append(f'*(float *)&a[{slot}]')
            slot += 1
        else:
            args.append(f'({t})a[{slot}]')
            slot += 1
    if slot * SLOT != argbytes:
        problems.append(f'{name}: prototype has {slot * SLOT} bytes of arguments, the table says {argbytes}')
    call = f'{name}( {", ".join(args)} )' if args else f'{name}()'
    if ret.replace(' ', '') in ('void', 'VOID'):
        lines.append(f'static ULONG_PTR {fn}( const ULONG_PTR *a ) {{ {call}; return 0; }}')
    elif ret.endswith('*') or wide:
        # Win64 results are 64-bit (rax): pointer-sized types (HWND,
        # LRESULT, ULONG_PTR) keep their upper half.
        lines.append(f'static ULONG_PTR {fn}( const ULONG_PTR *a ) {{ return (ULONG_PTR){call}; }}')
    else:
        lines.append(f'static ULONG_PTR {fn}( const ULONG_PTR *a ) {{ return (ULONG_PTR)(ULONG){call}; }}')
    thunks.append(fn)

first = entries[0][0]
lines += ['', f'const unsigned int win32u_syscall_first = {first:#x};',
          f'const unsigned int win32u_syscall_count = {len(entries)};',
          'ULONG_PTR (*const win32u_syscall_thunks[])( const ULONG_PTR * ) =', '{']
lines += [f'    {t},' for t in thunks]
lines += ['};', '']
open(out_path, 'w').write('\n'.join(lines))
# Names by number, for the host's tracing and statistics.
import json
json.dump({f'{sid:#x}': name for sid, name, _ in entries}, open(os.path.splitext(out_path)[0] + '.json', 'w'))
for p in problems:
    print(f'gen-syscalls.py: {p}', file=sys.stderr)
print(f'gen-syscalls.py: {len(entries)} system calls, {len(entries) - len(stubs)} implemented', file=sys.stderr)
