// Generates the OpenGL ES 3.0 calls opengl32 (gl4es) makes on the host's
// WebGL 2 (runtime/wine/webgl.mjs), from the prototypes in GLES3/gl3.h:
//
//   node native/opengl32-webgl/gen-gles.mjs gl3.h guest > gles_thunks.c
//   node native/opengl32-webgl/gen-gles.mjs gl3.h host > runtime/wine/gles-table.mjs
//
// The guest side is one function per entry point that packs its arguments
// into 32-bit words (floats by their bits, 64-bit integers as two words) and
// makes a unix call with the function's number; the host side is the table
// of names and argument kinds that decodes them. Functions in SPECIAL are
// written by hand in gles.c (strings and buffer mapping go through guest
// memory the host cannot allocate).
import { readFileSync } from 'node:fs';

const [header, side] = process.argv.slice(2);
const SPECIAL = new Set([
  'glGetString', 'glGetStringi', 'glMapBufferRange', 'glUnmapBuffer', 'glFlushMappedBufferRange', 'glGetBufferPointerv',
]);
/** Unix call codes: 0x1100 + the function's index (gles.h GLES_CALL_BASE). */
const BASE = 0x1100;

const fns = [];
for (const m of readFileSync(header, 'latin1').matchAll(/GL_APICALL\s+([\w\s*]+?)\s*GL_APIENTRY\s+(gl\w+)\s*\(([^)]*)\)\s*;/g)) {
  const [, ret, name, params] = m;
  const ps = params.trim() === 'void' || !params.trim() ? [] : params.split(',').map((p) => p.trim());
  const kind = (t) => (/\*/.test(t) || /\bGLsync\b/.test(t) ? 'p' : /\bGL(u)?int64\b/.test(t) ? 'q' : /\bGL(float|clampf)\b/.test(t) ? 'f' : 'i');
  const types = ps.map((p) => p.replace(/\s*\b\w+$/, '').trim());
  fns.push({ name, ret: ret.trim(), rkind: ret.trim() === 'void' ? 'v' : kind(ret), types, kinds: types.map(kind).join('') });
}

if (side === 'host') {
  const rows = fns.map((f) => `  ['${f.name}', '${f.rkind}', '${f.kinds}'],`);
  process.stdout.write(`// Generated by native/opengl32-webgl/gen-gles.mjs from GLES3/gl3.h: the
// OpenGL ES 3.0 functions opengl32 calls on the host, by unix call code
// GLES_CALL_BASE + index: [name, return kind, argument kinds]. Kinds: i a
// 32-bit integer or enum, f a float (its bits), p a guest pointer, q a 64-bit
// integer (two words), v nothing.
export const GLES_CALL_BASE = 0x${BASE.toString(16)};
export const GLES_FUNCTIONS = [
${rows.join('\n')}
];
`);
} else {
  const out = [
    '/* Generated by gen-gles.mjs from GLES3/gl3.h: OpenGL ES 3.0 calls made on the host. */',
    '#include "gles.h"',
    '',
  ];
  fns.forEach((f, id) => {
    if (SPECIAL.has(f.name)) return;
    const words = [...f.kinds].reduce((n, k) => n + (k === 'q' ? 2 : 1), 0);
    const params = f.types.length ? f.types.map((t, i) => `${t} a${i}`).join(', ') : 'void';
    const body = [`    DWORD w[${words + 1}];`];
    let k = 1;
    [...f.kinds].forEach((kind, i) => {
      if (kind === 'f') body.push(`    memcpy(&w[${k++}], &a${i}, 4);`);
      else if (kind === 'q') {
        body.push(`    w[${k++}] = (DWORD)a${i};`, `    w[${k++}] = (DWORD)((UINT64)a${i} >> 32);`);
      } else body.push(`    w[${k++}] = (DWORD)(ULONG_PTR)a${i};`);
    });
    body.push(`    gles_call(0x${(BASE + id).toString(16)}, w);`);
    if (f.rkind !== 'v') body.push(`    return (${f.ret})(ULONG_PTR)w[0];`);
    out.push(`static ${f.ret} GL_APIENTRY t_${f.name}(${params})`, '{', ...body, '}', '');
  });
  out.push('const struct gles_entry gles_entries[] =', '{');
  for (const f of fns) out.push(`    {"${f.name}", (void *)${SPECIAL.has(f.name) ? 'g' : 't'}_${f.name}},`);
  out.push('    {NULL, NULL},', '};', '');
  process.stdout.write(out.join('\n'));
}
