/*
 * opengl32.dll for WebWindows on WebGL 2.
 *
 * Desktop OpenGL (1.x to 2.1 and the extensions of the era, fixed function
 * included) comes from gl4es (https://github.com/ptitSeb/gl4es, MIT),
 * which turns it into OpenGL ES; the ES calls run on the browser's WebGL 2
 * in the host (runtime/wine/webgl.mjs), one unix call each (gles_thunks.c,
 * generated by gen-gles.mjs). This file is WGL: contexts, pixel formats and
 * buffer swaps.
 *
 * The host has one WebGL 2 context, whose drawing buffer is resized to the
 * client area of the window made current. A swap reads the frame back and
 * draws it into the window with GDI.
 *
 * Copyright 2026 the WebWindows authors
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */
#include <stdio.h>
#include <stdlib.h>
#include "gles.h"
#include "gl4esinit.h"

struct context
{
    HDC hdc;
    HWND hwnd;
    int width, height;
};

static HMODULE self;
static struct context *current;
static int pixel_format;
static BOOL gl4es_ready;
static BYTE *frame;
static size_t frame_size;

void APIENTRY_GL4ES gl4es_pre_swap(void);
void APIENTRY_GL4ES gl4es_post_swap(void);

static void *APIENTRY_GL4ES get_proc(const char *name)
{
    return gles_proc(name);
}

static void APIENTRY_GL4ES main_fb_size(int *width, int *height)
{
    *width = current ? current->width : 1;
    *height = current ? current->height : 1;
}

static void client_size(HWND hwnd, int *width, int *height)
{
    RECT r;

    if (!hwnd || !GetClientRect(hwnd, &r))
        SetRectEmpty(&r);
    *width = r.right - r.left > 0 ? r.right - r.left : 1;
    *height = r.bottom - r.top > 0 ? r.bottom - r.top : 1;
}

/* Sizes the host's drawing buffer to the current window. */
static void make_current(struct context *c)
{
    DWORD w[4];

    client_size(c->hwnd, &c->width, &c->height);
    w[1] = (DWORD)(ULONG_PTR)c->hwnd;
    w[2] = c->width;
    w[3] = c->height;
    gles_call(GLES_MAKE_CURRENT, w);
}

HGLRC WINAPI wglCreateContext(HDC hdc)
{
    struct context *c;
    DWORD w[1];

    if (!gles_init(self) || gles_call(GLES_OPEN, w))
    {
        SetLastError(ERROR_INVALID_PIXEL_FORMAT);
        return NULL;
    }
    if (!(c = calloc(1, sizeof(*c))))
        return NULL;
    c->hdc = hdc;
    c->hwnd = WindowFromDC(hdc);
    return (HGLRC)c;
}

HGLRC WINAPI wglCreateLayerContext(HDC hdc, int layer)
{
    return layer ? NULL : wglCreateContext(hdc);
}

BOOL WINAPI wglMakeCurrent(HDC hdc, HGLRC rc)
{
    current = (struct context *)rc;
    if (!current)
        return TRUE;
    current->hdc = hdc;
    current->hwnd = WindowFromDC(hdc);
    make_current(current);
    if (!gl4es_ready)
    {
        /* gl4es reports what it found on stdout unless told not to (the
         * program's LIBGL_* settings win). */
        if (!getenv("LIBGL_NOBANNER"))
            _putenv("LIBGL_NOBANNER=1");
        set_getprocaddress(get_proc);
        set_getmainfbsize(main_fb_size);
        initialize_gl4es();
        gl4es_ready = TRUE;
    }
    return TRUE;
}

BOOL WINAPI wglDeleteContext(HGLRC rc)
{
    if (!rc)
        return FALSE;
    if (current == (struct context *)rc)
        current = NULL;
    free(rc);
    return TRUE;
}

HGLRC WINAPI wglGetCurrentContext(void)
{
    return (HGLRC)current;
}

HDC WINAPI wglGetCurrentDC(void)
{
    return current ? current->hdc : NULL;
}

BOOL WINAPI wglShareLists(HGLRC a, HGLRC b)
{
    return TRUE; /* One host context: everything is shared. */
}

BOOL WINAPI wglCopyContext(HGLRC src, HGLRC dst, UINT mask)
{
    return FALSE;
}

static BOOL swap(HDC hdc)
{
    BITMAPINFO bmi;
    int width, height;
    size_t size;
    DWORD w[4];

    if (!current)
        return FALSE;
    gl4es_pre_swap();
    width = current->width;
    height = current->height;
    size = (size_t)width * height * 4;
    if (size > frame_size)
    {
        free(frame);
        frame_size = 0;
        if (!(frame = malloc(size)))
            return FALSE;
        frame_size = size;
    }
    w[1] = width;
    w[2] = height;
    w[3] = (DWORD)(ULONG_PTR)frame;
    if (!gles_call(GLES_PRESENT, w))
    {
        memset(&bmi, 0, sizeof(bmi));
        bmi.bmiHeader.biSize = sizeof(bmi.bmiHeader);
        bmi.bmiHeader.biWidth = width;
        bmi.bmiHeader.biHeight = height; /* bottom-up, as GL reads it */
        bmi.bmiHeader.biPlanes = 1;
        bmi.bmiHeader.biBitCount = 32;
        bmi.bmiHeader.biCompression = BI_RGB;
        SetDIBitsToDevice(hdc ? hdc : current->hdc, 0, 0, width, height, 0, 0, 0, height, frame, &bmi,
                DIB_RGB_COLORS);
    }
    gl4es_post_swap();
    /* The window may have been resized. */
    {
        int cw, ch;

        client_size(current->hwnd, &cw, &ch);
        if (cw != current->width || ch != current->height)
            make_current(current);
    }
    return TRUE;
}

BOOL WINAPI wglSwapBuffers(HDC hdc)
{
    return swap(hdc);
}

BOOL WINAPI wglSwapLayerBuffers(HDC hdc, UINT planes)
{
    return swap(hdc);
}

DWORD WINAPI wglSwapMultipleBuffers(UINT n, const WGLSWAP *swaps)
{
    return n && swap(swaps[0].hdc) ? n : 0;
}

/* One pixel format: double-buffered 32-bit RGBA with 24-bit depth and 8-bit
 * stencil, what the WebGL 2 context has. */
static void describe(PIXELFORMATDESCRIPTOR *pfd)
{
    memset(pfd, 0, sizeof(*pfd));
    pfd->nSize = sizeof(*pfd);
    pfd->nVersion = 1;
    pfd->dwFlags = PFD_DRAW_TO_WINDOW | PFD_SUPPORT_OPENGL | PFD_DOUBLEBUFFER;
    pfd->iPixelType = PFD_TYPE_RGBA;
    pfd->cColorBits = 32;
    pfd->cRedBits = 8;
    pfd->cRedShift = 16;
    pfd->cGreenBits = 8;
    pfd->cGreenShift = 8;
    pfd->cBlueBits = 8;
    pfd->cAlphaBits = 8;
    pfd->cAlphaShift = 24;
    pfd->cDepthBits = 24;
    pfd->cStencilBits = 8;
    pfd->iLayerType = PFD_MAIN_PLANE;
}

int WINAPI wglChoosePixelFormat(HDC hdc, const PIXELFORMATDESCRIPTOR *pfd)
{
    return 1;
}

int WINAPI wglDescribePixelFormat(HDC hdc, int format, UINT size, PIXELFORMATDESCRIPTOR *pfd)
{
    if (pfd && size >= sizeof(*pfd) && format == 1)
        describe(pfd);
    return 1;
}

int WINAPI wglGetPixelFormat(HDC hdc)
{
    return pixel_format;
}

BOOL WINAPI wglSetPixelFormat(HDC hdc, int format, const PIXELFORMATDESCRIPTOR *pfd)
{
    if (format != 1)
        return FALSE;
    pixel_format = format;
    return TRUE;
}

PROC WINAPI wglGetProcAddress(LPCSTR name)
{
    return (PROC)gl4es_GetProcAddress(name);
}

PROC WINAPI wglGetDefaultProcAddress(LPCSTR name)
{
    return NULL;
}

BOOL WINAPI wglUseFontBitmapsA(HDC hdc, DWORD first, DWORD count, DWORD base)
{
    return FALSE;
}

BOOL WINAPI wglUseFontBitmapsW(HDC hdc, DWORD first, DWORD count, DWORD base)
{
    return FALSE;
}

BOOL WINAPI wglUseFontOutlinesA(HDC hdc, DWORD first, DWORD count, DWORD base, FLOAT dev, FLOAT ext, int format,
        LPGLYPHMETRICSFLOAT gmf)
{
    return FALSE;
}

BOOL WINAPI wglUseFontOutlinesW(HDC hdc, DWORD first, DWORD count, DWORD base, FLOAT dev, FLOAT ext, int format,
        LPGLYPHMETRICSFLOAT gmf)
{
    return FALSE;
}

BOOL WINAPI wglDescribeLayerPlane(HDC hdc, int format, int plane, UINT size, LPLAYERPLANEDESCRIPTOR lpd)
{
    return FALSE;
}

int WINAPI wglSetLayerPaletteEntries(HDC hdc, int plane, int start, int count, const COLORREF *entries)
{
    return 0;
}

int WINAPI wglGetLayerPaletteEntries(HDC hdc, int plane, int start, int count, COLORREF *entries)
{
    return 0;
}

BOOL WINAPI wglRealizeLayerPalette(HDC hdc, int plane, BOOL realize)
{
    return FALSE;
}

BOOL WINAPI DllMain(HINSTANCE instance, DWORD reason, LPVOID reserved)
{
    if (reason == DLL_PROCESS_ATTACH)
    {
        self = instance;
        DisableThreadLibraryCalls(instance);
    }
    return TRUE;
}
